### ISSUE TITLE
Import not found: stringify

### ISSUE THREAD

**Issue by dsciamma** [nuxt-modules/strapi#215]
### Version
@nuxtjs/strapi: 1.1.0-27375403.70d78ef
nuxt: 3.0.0-27374259.21b664c

### Reproduction Link
I'm unable to use this version as qs.stringify seems to not be imported properly.

**Comment by dsciamma** [comment]
Sorry, I created the ticket as I couldn't find it in the list.
I'll try 1.1.0 again then (even if I was interested in the querystring support for parameters 😁).

**Comment by benjamincanac** [comment]
No problem! We'll release a `1.2.0` version with the querystring support and the migration to `@nuxt/module-builder` asap.

**Comment by benjamincanac** [comment]
@dsciamma This should now be fixed in latest edge version, let me know if you still have the bug.
