### ISSUE TITLE
Does Strapi-Nuxt have any "Query Engine or filtering support" via REST

### ISSUE THREAD

**Issue by jswhisperer** [nuxt-modules/strapi#251]
https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/query-engine-api.html#query-engine-api

Is it only possible with something like graphql, even though nuxt runs a nodejs server in certain modes?

Is it possible to find an entity by something other than ID for example using the aforementioned API and the Strapi-Nuxt Library wrapper?

**Comment by benjamincanac** [comment]
Yes you can achieve this but it's not related to the nuxt module as it's only a wrapper on top of your Strapi API. Take a look at https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest-api.html#api-parameters, all these query parameters can be used like this:

```vue
<script setup>
const { find } = useStrapi4()

const { data: restaurants } = await useAsyncData('restaurants', () => find('restaurants', { populate: 'logo', pagination: { start: 0, limit: 4 }, filters: { ... } }))
</script>
```
