### ISSUE TITLE
Make cookie name configurable

### ISSUE THREAD

**Issue by TitusKirch** [nuxt-modules/strapi#262]
### Is your feature request related to a problem? Please describe.
Currently the name of the cookie is "strapi_jwt" and hardcoded. For example, we have extended Strapi with a refresh and access token system, which is why we would like to change the cookie name from "strapi_jwt" to "access_token".

### Describe the solution you'd like
I would like to be able to configure the name of the cookie via nuxt.config.ts.

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by Intevel** [comment]
@TitusKirch Implemented this feature in #265 💚
