### ISSUE TITLE
ts can't figure out strapi interface

### ISSUE THREAD

**Issue by Slepzs** [nuxt-modules/strapi#268]
I cannot get this error to disappear, even though it works. 

I have a interface
```
 export interface Wine {
    id?: string;
    name?: string;
    producent?: string;
    country?: string;
    type?: string;
    drue?: string;
    flstr?: string;
    alkohol?: number;
  }
```

and a submit request

```
const onSubmit = async () => {
  const wine_data = {
      name: wine_name.value,
      producent: wine_producent.value,
      country: country.value,
      type: type.value,
      drue: drue.value,
      flstr: flStr.value,
      alkohol: parseInt(alkohol.value),
  }  
  await create<Strapi4Response<Wine>>('wines', {...wine_data as Wine });
}

```

But i keep getting this error

`Type '{ id?: string; name?: string; producent?: string; country?: string; type?: string; drue?: string; flstr?: string; alkohol?: number; }' has no properties in common with type 'Partial<Strapi4Response<Wine>>'`

Whats up with that? Thanks!

**Comment by harlan-zw** [comment]
This should be sorted with https://github.com/nuxt-modules/strapi/releases/tag/v1.6.0 and can be closed
