### ISSUE TITLE
How to add user "role"  when   call : 'await fetchUser()' ?

### ISSUE THREAD

**Issue by titoff002** [nuxt-modules/strapi#271]
Hello, 

```
const { fetchUser } = useStrapiAuth()
const user2 = await fetchUser()
```
Question : How to add user "role"  on the response FROM `await fetchUser() `??

I would like use "populate" :  but I don't understand how it works. Do you have an example ?

_**PS : i use nuxtjs 3.**_

Thanks.

**Comment by fskarmeta** [comment]
I also need this. I tried using the auth.populate params in nuxt config but not luck. Also seems that populating other relations do not work. I just get the default /me/ properties.

**Comment by fskarmeta** [comment]
Would be really nice to know if this is in the roadmap

**Comment by fskarmeta** [comment]
@titoff002 Hey, at least it works with useStrapiUser, you have to give permission to the role in strapi to find it's own role first. Then the nuxt.config.ts strapi config object add the `auth: {populate: ['role']}}` object.

**Comment by ZwurK** [comment]
Here is a solution:

- Modify your nuxt config :

```
strapi: {
    auth: {
      populate: ['role']
    }
},
```

- Don't forget to enable find and findOne role permissions for authenticated users in the users permissions plugin.
![Screenshot from 2023-08-16 11-00-23](https://github.com/nuxt-modules/strapi/assets/137521291/b515d078-0f29-4684-9627-880c5da73949)
