### ISSUE TITLE
Have documentation in vanilla/default javascript too instead of only in Typescript

### ISSUE THREAD

**Issue by AdrianoCahete** [nuxt-modules/strapi#273]
Today, all the examples are in typescript. I see the #221 issue, but there are a lot of questions in there, so I think it will be more productive to have another one just to track this.

> Can you still use this module with standard nuxt js (eg. this.$strapi.find() as with the older version)? 

Can we have the documentation in vanilla js too instead of just ts?

**Comment by benjamincanac** [comment]
Sorry but we won't be providing a version of the documentation without TypeScript.
