### ISSUE TITLE
Incompatibility issues when using Nuxt3

### ISSUE THREAD

**Issue by Mechse** [nuxt-modules/strapi#282]
Hello,

When using the provided nuxt3 setup guide:
https://v3.nuxtjs.org/getting-started/quick-start

This Nuxt3 version ist installed:
`"nuxt": 3.0.0-rc.9`

When building the project:
```
Module @nuxtjs/strapi is disabled due to incompatibility issues:
 - [nuxt] Nuxt version `^3.0.0 || ^2.16.0` is required but currently using `3.0.0-rc.9` 
```

So how is it possible to run this nuxt module with the current nuxt3 build?
Thanks,
Max

**Comment by gravitano** [comment]
Hi, I also have this issue. Done created PR [here](https://github.com/nuxt-modules/strapi/pull/281) hopefully can be merge.

**Comment by Atinux** [comment]
Working perfectly with latest Nuxt 3
