### ISSUE TITLE
Problem accessing single types

### ISSUE THREAD

**Issue by jiblett1000** [nuxt-modules/strapi#287]
### Version
- Operating System: `Linux`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.12-27736489.2e080c2`
- Nitro Version:    `0.5.4-27726613.640c2b7`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `typescript`, `css`, `modules`, `experimental`, `image`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.3`, `@pinia/nuxt@0.4.2`, `@vueuse/nuxt@9.3.0`, `@nuxt/image-edge@1.0.0-27719579.87dcdf2`, `unplugin-icons/nuxt`, `@nuxtjs/strapi@1.6.1`
- Build Modules:    `-`

### Reproduction Link

n/a

### Steps to reproduce

Try to access a "single type" from strapi using find.

### What is Expected?

I would expect to be able to get a single type (i.e. /api/homepage) without type errors.

### What is actually happening?

So, after looking through the module code, it seems that neither `find()` or `findOne()` are appropriate for getting "single types" from strapi. The problem...

- `find()` is meant to return an array. Single types return an object so this throws a type error complaining it's not an array.
- `findOne()` returns an object. That's great and seems more appropriate than `find()` semantically speaking. However, it requires an `id` argument, which is then used in a template literal to add it onto the end of the content type argument. This is a problem because single types don't use an `id` in the url.

#### Solutions?

- I would say the easiest might be to just add another method like `getSingle()` (or something with a better name) that doesn't require an `id` as an argument but still returns the same type as `findOne`.
- A more ideal solution I feel would be to have `id` as an optional parameter in `findOne()`, however based on my brief venture down that rabbit hole, this would require a lot more work and introducing maybe "rest parameters" or something similar. I'm hoping there's something I'm not aware of that would allow this.

#### Side Note:

On a somewhat related note (I'm happy to create a separate issue if need be), It seems to me that while not the end of the world, the methods `find()` and `findOne()` could maybe be renamed to `getEntries()` and `getEntry()`. My reasoning:

- The new names would be more inline with how strapi refer to their api (i.e. "get entries" and "get an entry" ).
- `findOne()` isn't horrible but `find()` doesn't provide any additional insight into what it might be returning, while `getEntries()` is most likely returning an array if I had to guess.

Again, not the end of the world here, but I feel new naming would provide more consistency and clarity, albeit a slightly more verbose solution.

**Comment by benjamincanac** [comment]
Hello @jiblett1000,

Sorry for the delay!

I've made the `id` parameter optional for `findOne`, `update` and `delete` methods so you should not have issues with types anymore.

The `find` and `findOne` methods are based on nam``

**Comment by jiblett1000** [comment]
@benjamincanac No worries! Thanks for getting that fix in :)

**Comment by wojtekpiskorz** [comment]
@benjamincanac so... is it possible to use findOne to get a /blog/slug instead of /blog/id?

I'm doing it like this now: 
```
const articles = await find<Article>(`articles?populate=featuredImage&filters[slug][$eq]=${route.params.slug}`);
const article = articles.data[0];
```
But this is poor for error handling

**Comment by jiblett1000** [comment]
> @benjamincanac so... is it possible to use findOne to get a /blog/slug instead of /blog/id?
> 
> I'm doing it like this now:
> 
> ```
> const articles = await find<Article>(`articles?populate=featuredImage&filters[slug][$eq]=${route.params.slug}`);
> const article = articles.data[0];
> ```
> 
> But this is poor for error handling

Couldn't say for sure, but I don't think the default strapi behavior will allow that. I found this thread though. Might be something useful in there for you:

https://forum.strapi.io/t/strapi-v4-search-by-slug-instead-id/13469/34

**Comment by benjamincanac** [comment]
@wojtekpiskorz Using `findOne` to get by slug is possible but you'll have to override your strapi controller, if you do so you can use the module as such:

```ts
await findOne<Article>('articles', route.params.slug, { populate: ['featuredImage'] })
```
