### ISSUE TITLE
useStrapiAuth is POST as 'text/plain' instead of 'application/json'

### ISSUE THREAD

**Issue by AdrianoCahete** [nuxt-modules/strapi#296]
### Version
@nuxtjs/strapi: 1.6.3
nuxt: 3.0.0

strapi is on Strapi Cloud, nuxt is on render

### Reproduction Link
https://acx.onrender.com/auth/login

### Steps to reproduce
Try any login/password and see the request to api (yes, the form is open/no captcha, I know).

### What is Expected?
According Strapi forums, correct way is to use [application/json](https://forum.strapi.io/t/error-405-on-strapi-request/5017/2).

### What is actually happening?
Result is "405 Method Not Allowed".

**Comment by benjamincanac** [comment]
Hello @AdrianoCahete,

Just tried your reproduction, the `Content-Type` is well set to `application/json` on my side but there is a CORS error.

**Comment by AdrianoCahete** [comment]
Yep, I forgot to close/delete this issue. Fixed the content type, but had another error with CORS :(
