### ISSUE TITLE
feature: changePassword method

### ISSUE THREAD

**Issue by jiblett1000** [nuxt-modules/strapi#311]
### Is your feature request related to a problem? Please describe.

The only way to change the password currently using the module is to use the `resetPassword` method. This requires a code that is emailed to the end user along with the password and password confirmation. However, as you can see here:

https://docs.strapi.io/developer-docs/latest/plugins/users-permissions.html#reset-password

...there is another endpoint `change-password` that has a "currentPassword" parameter alongside "password" and "passwordConfirmation". This is useful if a user is logged into their account and want to change their password from a settings page (for example). 

### Describe the solution you'd like

Considering there is a method for the `reset-password` endpoint, I think it seems reasonable to add one for the `change-password` endpoint as well.

### Describe alternatives you've considered

This is entirely possible (and not terribly hard to do) using the `useStrapiClient` composable, but as stated above; considering there is a `resetPassword` method, I think it makes sense for there to be a `changePassword` one as well.

### Additional context

Thank for the consideration!

**Comment by benjamincanac** [comment]
Hello @jiblett1000,

Thanks for the suggestion!

I just pushed this https://github.com/nuxt-modules/strapi/commit/00b7915137582af6a8a0e177ac23ba30acb70a20, would you be able to try it out on the edge channel before the release? I don't have a Strapi v4 running at the moment to do it myself.

**Comment by jiblett1000** [comment]
@benjamincanac Thanks for adding that :) It's throwing a type error on my end (that the method doesn't exist on the composable), but functionally it seems to be working in my project.

**Comment by jiblett1000** [comment]
@benjamincanac Wait, scratch that. I restarted my editor and no type error. All is well :)

**Comment by benjamincanac** [comment]
Thanks for testing 😊 Should be available in [v1.7.1](https://github.com/nuxt-modules/strapi/releases/tag/v1.7.1).
