### ISSUE TITLE
docs: error plugin

### ISSUE THREAD

**Issue by jiblett1000** [nuxt-modules/strapi#315]
### Version
@nuxtjs/strapi:  v1.7.1 
nuxt: v3.1.2 

Hello,

In the error reporting section where the docs show an example of adding a plugin, it currently is this:

```ts
import type { Strapi4Error } from '@nuxtjs/strapi'
import { defineNuxtPlugin } from '#app'

export default defineNuxtPlugin((nuxt) => {
  nuxt.hooks.hook('strapi:error' as any, (e: Strapi4Error) => {
    nuxt.$toast.error({ title: e.error.name, description: e.error.message })
  })
})
```

However, the type Strapi4Error is not available on that path. This import path works however: `@nuxtjs/strapi/dist/runtime/types`

Also, importing defineNuxtPlugin is not necessary.

So, this could perhaps be rewritten to this:

```ts
import type { Strapi4Error } from "@nuxtjs/strapi/dist/runtime/types";

export default defineNuxtPlugin((nuxt) => {
  nuxt.hooks.hook("strapi:error" as any, (e: Strapi4Error) => {
    nuxt.$toast.error({ title: e.error.name, description: e.error.message })
  });
});
```

**Comment by jiblett1000** [comment]
P.S. The same goes for the v3 example I guess

**Comment by badalya1** [comment]
P.S. `nuxt.hooks.hook(...)` is not necessary. `nuxt.hook(...)` is enough. 

From [Nuxt documentation](https://nuxt.com/docs/guide/going-further/hooks#usage-with-plugins).

**Comment by benjamincanac** [comment]
Thanks for spotting this, documentation has been updated! 😊
