### ISSUE TITLE
Nuxt3, Strapi, Docker: [Vue warn]: Unhandled error during execution of setup function

### ISSUE THREAD

**Issue by Periton-Media** [nuxt-modules/strapi#316]
### Version
@nuxtjs/strapi: "^1.7.1"
nuxt: "^3.2.0"

### Reproduction Link

I don't think there's a way that I can provide a reproduction link. This error only happens when using a production build of the dockerized application.

The code that fails is this one:
```
import { Insight } from "~~/types";

const { find } = useStrapi();

const response = await find<Insight>("insights");
console.log(response);
```

Especially the line `const response = await find<Insight>("insights");`

Everything works fine in development mode with only Strapi and the DB running in a docker container.

### Steps to reproduce

- Dockerize nuxt app
- Dockerized production version of Strapi

### What is Expected?

The app should just fetch the data and get on with it.

### What is actually happening?

When using the containerized version of the Nuxt app it prints the error
"[Vue warn]: Unhandled error during execution of setup function" and the app shows "Error 500"

One fix is to just wrap the code with a try/catch block. This leads to more strange behavior.
Now the data is fetched just fine and gets printed to the browser console, the app just shows up like it should. The docker console however still shows that there is an unknown error:

```
{
  error: {
    status: 500,
    name: 'UnknownError',
    message: 'fetch failed ()',
    details: FetchError: fetch failed ()
        at async file:///app/.output/server/chunks/app/server.mjs:866:14
        at async setup (file:///app/.output/server/chunks/app/_nuxt/default-8e6c9cee.mjs:91:98)
  }
}
```

It seems to execute both the try-code and the catch-code.

I absolutely don't know what to do lol. I'm not even sure if this is an error with this module or with my setup.

Mby one of you can help. If not, feel free to just close this - I don't think there's much you guys can do here tbh; it just seems like the strangest bug ever to me.

#### Update:

It also works fine when doing a regular build without docker and running that using node fetching data from the strapi-container. Both the browser-console and the normal console show no errors.

#### Update 2:

Figured out the problem. It seems like it has to do with the client-side and server-side going out of sync. The server-side inside the container can't reach the strapi container via localhost:1337 and throws the error. The client-side has no problem reaching the container via localhost since the ports are exposed.

So if anyone has an idea to fix that I would greatly appreciate it. Otherwise please close this issue; this really isn't a problem with the module.

**Comment by Periton-Media** [comment]
I realized that I'm an idiot and that this problem just fixes itself when actually moving to production since all of the calls to the strapi api can then be made via a request to the actual url and not any weird localhost things. Sorry guys, it's just late where I live, going to sleep now :) Closing this.

Thanks for this awesome module btw and all the people maintaining it.

**Comment by jakhsu** [comment]
Hi @PeritonM I just encountered similar problem here. I'm trying out fetching data from strapi in a nuxt3 app and my setup is very minimal and just doing the example code per https://docs.strapi.io/dev-docs/integrations/nuxt-js

If the problem only goes away when not in dev mode, how did you manage to develop and debug?

**Comment by cobsen** [comment]
@jakhsu I had the same issue with a very basic setup. Then I realized that I had to allow public access to the content-type I was trying to fetch inside my script setup
