### ISSUE TITLE
`filters` prop usage

### ISSUE THREAD

**Issue by warflash** [nuxt-modules/strapi#333]
Hey 👋
Just wondering someone could give an example on how to use the `filters` property for `find()`. 
Tried looking for examples in the docs and the source itself, though I couldn't find anything yet.
The typing the field has with `Record<string, unknown>` unfortunately doesn't tell much

Appreciate the help!

**Comment by kwiat1990** [comment]
`find` takes a Strapi collection’s name as first parameter and an parameters object as the second one. For all available option see [Strapi docs](https://docs.strapi.io/dev-docs/api/rest/parameters). 

In my project i use it as follows: 
```ts

const getArticlesByCategory = async (category: string) => {
  const { find } = useStrapi();
  const params = {
    filters: {
      category: {
        slug: { $in: [category] },
      },
    },
  };

  return await find<Article >("articles", params);
};
```

**Comment by molul** [comment]
Sorry for hijacking the thread, but I'm struggling to understand how this works.

For reference, in my Strapi instance there's a content type called Musico, and among its attributes there's "divTerr2", which corresponds to cities (i.e.: "Madrid").

So I'm able to get a list of "Musicos" with pagination and sorting, but when I use filters I get 0 entried. Here's my current attempt:

```
const {
  data: musicians,
  pending,
  error,
  refresh
} = await useAsyncData('allMusicians', () => {
  return find<Musico>('musicos', {
    pagination: { page: page.value, pageSize: pageSize.value },
    filters: {
      divTerr2: { slug: { $eq: 'Madrid' } }
    },
    sort: 'username_lc:asc'
  })
})
```

By URL, this works https://<Strapi_URL>/api/musicos?filters[divTerr2][$eq]=Madrid

Also tried with this filters object:

```
    filters: {
      divTerr2: {  $eq: 'Madrid' }
    },
```

but no luck yet. What am I missing?
