### ISSUE TITLE
Request to public API with authenticated user doesn't work without explicit permission

### ISSUE THREAD

**Issue by kwiat1990** [nuxt-modules/strapi#336]
### Version
@nuxtjs/strapi: 1.9.0
nuxt: 3.3.3

### Steps to reproduce
1. Grant public access to some collection in Strapi
2. In Nuxt, fetch data from that collection as anonymous user -> it should work.
3. Logi-in with login provider or default login, so you have Strapi JWT.
4. Fetching mentioned collection doesn't work anymore. An authenticated user must have permission to access such a collection -> more overhead in Strapi as same permissions for a given collection must be duplicated: for public user and authenticated one.

### What is Expected?
Public collections should be available to all users without the need to duplicate permission in Strapi. This could be achieved with an additional flag, which would force a request without the access token.

**Comment by benjamincanac** [comment]
@kwiat1990 How is this related to the nuxt module? You would encounter the same by doing http calls with CURL to your API.

**Comment by kwiat1990** [comment]
Yes but while doing CURL I decide by myself what headers I want to send in what context. Using Strapi module every call automatically contain authorization header after user logged in, which often is either unnecessary or even unwanted. In case of Strapi it requires extra work to enable the same permissions for authenticated user, which are already set for public access. If there's more than one kind of authenticated role, it requires even more work and tends to be error prone if some permission changed and needs to be changed for all authenticated roles.

**Comment by benjamincanac** [comment]
You're right, I see the issue. Will work on it asap to be able to override auth then!

**Comment by benjamincanac** [comment]
Still thinking this through, you could achieve this without any update on the module:

```ts
const client = useStrapiClient()

await client('/restaurants', {
  headers: {
    Authorization: null
  }
})
```
