### ISSUE TITLE
Use custom Strapi Admin URL suffix instead of /admin

### ISSUE THREAD

**Issue by Striffly** [nuxt-modules/strapi#343]
### Is your feature request related to a problem? Please describe.
By default, when starting project in dev mode, the Strapi Admin Url that is shown in console is `http://localhost:1337/admin/`.
However, admin URL can be customized / different in Strapi (ex : http://localhost:1337/dashboard/). 

### Describe the solution you'd like
Add option to customize Strapi Admin URL suffix

**Comment by Zignature** [comment]
I fixed it for myself 😄 

You have to edit a view files.

in `node_modules/@nuxtjs/strapi/dist/module.mjs`
*  add `admin: "/admin",` to the `defaults` section:

```javascript
  defaults: {
    url: process.env.STRAPI_URL || "http://localhost:1337",
    prefix: "/api",
    admin: "/admin",
    version: "v4",
    cookie: {},
    auth: {},
    cookieName: "strapi_jwt",
    devtools: false
  }
```
* change: `const adminUrl = joinURL(nuxt.options.runtimeConfig.public.strapi.url, "/admin/");`
  to: `const adminUrl = joinURL(nuxt.options.runtimeConfig.public.strapi.url, nuxt.options.runtimeConfig.public.strapi.admin);`

in `node_modules/@nuxtjs/strapi/dist/module.d.mts` and `node_modules/@nuxtjs/strapi/dist/module.d.ts`
Edit the `interface ModuleOptions`.
add:

```typescript
/**
* Strapi Admin Prefix
* @default '/admin'
* @type string
*/
admin?: string;

```

in `nuxt.config.ts` add `admin: '/dashboard',`  to the `strapi` section:

```javascript
strapi: {
  url: process.env.STRAPI_URL || 'http://localhost:1337',
  prefix: '/api',
  admin: '/dashboard',
  version: 'v4',
  cookie: {},
  cookieName: 'strapi_jwt',
  devtools: true
},
```

Restart both your strapi backend and your nuxt frontend. Now you can use a custom admin url and you'll be able to run the strapi dashboard in NuxtDevtools

**Comment by Striffly** [comment]
Oh thank you very much ?
Do you want to send a PR for this ? Or can I do it for you ?

**Comment by Zignature** [comment]
Go ahead and do it 😄

**Comment by Zignature** [comment]
You did the PR 👍🏽

**Comment by Zignature** [comment]
@Striffly congrats! It got merged 🥂  😄
