### ISSUE TITLE
npx only-allow pnpm

### ISSUE THREAD

**Issue by ilockruoyi** [nuxt-modules/strapi#344]
### Version
@nuxtjs/strapi: 
nuxt: 

### What is actually happening?
When I npm install @nuxtjs/strapi --save-dev according to the document  said.
It asks for pnpm.
I hope it's not checked when it's a dependency
The document address is https://strapi.nuxtjs.org/setup

**Comment by ilockruoyi** [comment]
it is ok when I npm dependency for version 1.9.1

**Comment by benjamincanac** [comment]
When switching to `pnpm` I added a `preinstall` script with `npx only-allow pnpm` but it should only apply when installing the dependencies inside the module itself.

I just tested with both `npm` and `yarn` but didn't encounter the issue. Do you have a reproduction?

**Comment by benjamincanac** [comment]
I'm not sure why this happens, but I just published a `1.9.3` without this `preinstall` script!
