### ISSUE TITLE
pm2 run localhost url rather than strapi production url

### ISSUE THREAD

**Issue by sakamichi46-online** [nuxt-modules/strapi#345]
### Version
@nuxtjs/strapi: "^1.9.3"
nuxt: "^3.4.3"

### Steps to reproduce
So I have a strapi app already in production, When we try build our front end app there is a bug in `@nuxtjs/strapi` , we are using pm2 production they listen to `http://127.0.0.1:1337` when using rather than our production ready strapi api. But it success when we using `npm run dev` they actually listen to our api.

### Nuxt Configuration
```
strapi: {
        url: process.env.STRAPI_URL , ##our env file with strapi api
        prefix: '/api',
        version: 'v4',

}
```

### Reproduce

1. pm2 start ecosystem.config.js
2. It error because listen to localhost
3. npm run dev
4. it works because it's listen to oru api strapi production

**Comment by benjamincanac** [comment]
Not really familiar with `pm2`, but did you specify environment variables inside your `ecosystem.config.js`?

```js
module.exports = {
  apps: [
    {
      env: {
        STRAPI_URL: '...'
      },
      env_production: {
        STRAPI_URL: '...'
      }
    }
  ]
}
```
