### ISSUE TITLE
use with virtual ip

### ISSUE THREAD

**Issue by ldiellyoungl** [nuxt-modules/strapi#346]
How can I use strapi url on virtual ip address?
-
Example:
my Nuxt and strapi project is running on real ip 10.106.0.79. 
On another device, the virtual address of the server is 11.11.0.2
Nuxt is working fine.
but strapi url is hardcoding or taken from .env and its not work

**Comment by BayBreezy** [comment]
Are you using nginx? You can check out this part of the strapi docs that speak to deployment: https://docs.strapi.io/dev-docs/deployment/optional-software-guides.
You may need to take a look at the server config. The docs show that you can update it like so:

```js
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: 'https://api.example.com',
});
```

You would need to set the Host value via `.env` or something like that. Also, if your IP address is public, you can set the url to point to it

**Comment by ldiellyoungl** [comment]
no, i dont use ngnix. i mean strapi url hardcoded in nuxt config setting plugin

**Comment by ldiellyoungl** [comment]
> Why don't you use the `strapi.url` config in your `nuxt.config.ts`?


i use. strapi server run on 10.106.0.79 and set in nuxt config strapi url

i mean on another device, the virtual address of the  strapi server  is 11.11.0.2. strapi url in nuxt config still 10.106.0.79

**Comment by ldiellyoungl** [comment]
So. I figured it out. If you want using strapi in secure network, just use proxy route rules like this

```JS
  routeRules: {
    '/api/**': { proxy: 'http://localhost:1337/api/**' } //or use .env
  },

  strapi: {
    url: '/api', 
    prefix: '',
  }
```
