### ISSUE TITLE
Usage with useAsyncData

### ISSUE THREAD

**Issue by konradsienkowski** [nuxt-modules/strapi#348]
Hi there, 

in the module documentation, there's information that the composables can be [wrapped in useAsyncData](https://strapi.nuxtjs.org/advanced#async-data) to "take full advantage of server-side rendering". It's quite a curt explanation, so I'd like to ask if anyone can expand on it. What are the main differences between using `find/findOne` directly and wrapping them in `useAsyncData`? 

Thanks

**Comment by benjamincanac** [comment]
Here is the documentation of Nuxt [useAsyncData](https://nuxt.com/docs/api/composables/use-async-data#useasyncdata).

> `useAsyncData` is a composable meant to be called directly in a setup function, plugin, or route middleware. It returns reactive composables and handles adding responses to the Nuxt payload so they can be passed from server to client without re-fetching the data on client side when the page hydrates.
