### ISSUE TITLE
Have images sent to .output during nuxt generate

### ISSUE THREAD

**Issue by KamiAmiga** [nuxt-modules/strapi#351]
Hello ! 

First of all, thank you for all the work on this very helpful module. 😃 
I am currently rebuilding my portfolio, with my Strapi running locally, and my Nuxt in a repo alongside. My goal is to use nuxt generate to build all the files that I'll push to my server.

My problem is : images are not part of the output, and the .html files are trying to use images located at the localhost:1337. I wasn't able to figure out the proper way to solve this : is it a custom code to make in my nuxt repo or some config in my Strapi to push the images at the right place or should I rely to an external solution ? What do you recommend for this please ?

If it can help, my Nuxt repo is the following : https://github.com/KamiAmiga/portfolio2023

Thanks !

**Comment by SvenWesterlaken** [comment]
There are two ways to copy images:

- Served in the public folder, this will be one on one be copied during a nuxt build
- Strapi provides url/paths where you can fetch them from the strapi backend through the API.

I guess you use the latter? And what you want is to replace your strapi URL of `localhost:1337` with the URL of your live strapi instance? If so, you should look into setting the configuration of the server URL: https://strapi.nuxtjs.org/advanced#server-specific-configuration.

Hope this helps.

**Comment by KamiAmiga** [comment]
Hi ! Thanks for your answer.
I've checked, and the images are currently in a public/uploads folder of my strapi backend.
According to the documentation you sent (+ what I found in strapi documentation) it looks like I have to deploy a live version of the Strapi backend so that I can use its new URL instead of the localhost one... which is what I haven't done currently.

**Comment by SvenWesterlaken** [comment]
Yes, that is correct. You will have two instances communicating over the internet to each other: your strapi instance & your nuxt instance. After you got both online make sure that you change the URL of strapi from nuxt and it should work as you have it locally.
