### ISSUE TITLE
How to define a :asc or :desc sort order when sorting

### ISSUE THREAD

**Issue by sevspo** [nuxt-modules/strapi#356]
```ts
const { find } = useStrapi<ServiceWithRelations>();

const { data } = await find('services', {
  populate: {
    icon: true,
  },
  sort: ['title:asc'],
});
```
the resulting query then is:
`services?populate[icon]=true&sort[0]=title%3Aasc`
and this does not work!

how can I get it to be as required
`services?populate[icon]=true&sort[0]=title:asc` ?

**Comment by SvenWesterlaken** [comment]
Which version are u using? the following code seems to be working for me:
```js
find('blog-pages', { populate: ['header_image'], sort: ['publishedAt:desc'] })
```

**Comment by sevspo** [comment]
Hello @SvenWesterlaken
Sorry for the late reply! I just upgraded to the latest version, 1.10.0 but the syntax above still does not work for me. The parser seems to not be able to resolv the : , so it produces the %3A instead. What can I do? I really need to sort some stuff in my app.

**Comment by SvenWesterlaken** [comment]
`%3A` is the URL encoded version` :`, perhaps searching around with that term and your strapi version should get you further.
