### ISSUE TITLE
How to integrate with github or google auth provider?

### ISSUE THREAD

**Issue by byoungd** [nuxt-modules/strapi#357]
I searched google and github but havn't found a example.

And the config is invalid`
    login: {
      providers: ['github'] // Strapi authentication providers
    }
` 
So how to implement this?

Thanks.

**Comment by benjamincanac** [comment]
Have you checked https://strapi.nuxtjs.org/auth#getproviderauthenticationurl and https://strapi.nuxtjs.org/auth#authenticateprovider?

**Comment by benjamincanac** [comment]
Did you configure your Strapi backend providers? You can check manually without the module by following this: https://docs.strapi.io/dev-docs/plugins/users-permissions#providers

**Comment by EmilyYond** [comment]
Hey @benjamincanac, thanks for getting back to me. I had - sorry my mistake was that I didn't realise there was an access token in the string so I was passing in the wrong token! Apologies, very stupid mistake to make 🤦‍♀️
