### ISSUE TITLE
user permissions plugin. Update request won't work

### ISSUE THREAD

**Issue by doubleyooz** [nuxt-modules/strapi#358]
### Version
@nuxtjs/strapi: ^1.9.3
nuxt: ^3.7.0

### Steps to reproduce
Have a strapi server v4 on and you need to be using user::permissions plugin to handle your users.
https://docs.strapi.io/dev-docs/plugins/users-permissions

try to update your user
```ts
const { update } = useStrapi();
await update('users', userId, { email: 'user@fmail.com' });

```
fail miserably.

### What is Expected?
You should be able to update your users.

### What is actually happening?
The requisition returns 200, but nothing is being updated. 'Why?' you ask.
For some reason the user:permissions plugin doesn't expect the data to be wrapped in a data object. They are not going against strapi guidelines, their logic is that they're doing the work for you, so you don't need to send your data wrapped in a data object.

The whole problem lies with this function, it always wraps the data inside a data object. So the user:permissions gets it and wraps under an additional data object. The requisition succeeds, but there's no nested data property to be found and updated, so nothing changes.

```ts
 const update = <T>(contentType: string, id: string | number | Partial<T>, data?: Partial<T>): Promise<T> => {
    if (typeof id === 'object') {
      data = id
      // @ts-ignore
      id = undefined
    }

    const path = [contentType, id].filter(Boolean).join('/')

    return client(path, { method: 'PUT', body: { data } })
  }

```

What I ask in behalf of the user:permissions plugin and of all those who want to go against strapi best-practices by building their own custom endpoints is an option, an optional option, to not wrap the data inside a data object. 

For now, here's the workaround

```ts
const client = useStrapiClient();
await client(`/users/${props.id}`, {
        method: 'PUT',
        body: { email: 'user@fmail.com' },
      });
```

**Comment by BayBreezy** [comment]
Hey @doubleyooz The way to update the `users` collection is with the `useStrapiClient` composable like so

```ts
const client = useStrapiClient();

await client("users", {
  method: "PUT",
  body: { email: "user@fmail.com" }
});
```

I think this is the case because this module wraps all the update requests in an object like so:

```ts
data: {
// your data gets spread here when passed to the `update` function
}
```

You can check out the signature of the update function here: https://github.com/nuxt-modules/strapi/blob/dev/src/runtime/composables-v4/useStrapi4.ts#L66

& here: https://github.com/nuxt-modules/strapi/blob/dev/src/runtime/composables-v4/useStrapi.ts#L9
