### ISSUE TITLE
Pagination not triggering request for new data with change in route variable passed as one of the props.

### ISSUE THREAD

**Issue by modbender** [nuxt-modules/strapi#361]
### Version
@nuxtjs/strapi: ^1.9.3
nuxt: 3.7.3

### Reproduction Link

Generic Issue

### Steps to reproduce

Use the below code to get data

```
const { data: postList, meta } = await find("posts", {
  pagination: {
    page: route.query?.page || 1,
    pageSize: 12,
  },
  populate: ["featuredImage", "tags"],
  sort: ["createdAt:desc"],
});
```

Going to
http://localhost:3000/

I click on a button  
that routes to http://localhost:3000/?page=2

but I see in browser Network tab no request has been sent for new data to be fetched and no changes in the data rendered.

I have also tried using `computed`

```
const currentPage = computed(() => route.query?.page || 1);

const { data: postList, meta } = await find("posts", {
  pagination: {
    page: currentPage.value,
    pageSize: 12,
  },
  populate: ["featuredImage", "tags"],
  sort: ["createdAt:desc"],
});

Still no change.
```

### What is Expected?

Either upon change in route query or `route` variable passed for `Strapi4RequestParams` the data fetch should be triggered to get new data.

### What is actually happening?

No data fetch is triggered on change in route query or reactive variable `route` passed for `Strapi4RequestParams`.

**Comment by benjamincanac** [comment]
You should use `useAsyncData` with the `watch` option for this, something like:

```ts
const { data } = await useAsyncData('posts', () => find('posts', {
  pagination: {
    page: currentPage.value,
    pageSize: 12
  },
  populate: ['featuredImage', 'tags'],
  sort: ['createdAt:desc']
}), {
  watch: [currentPage]
})
```

**Comment by modbender** [comment]
@benjamincanac Didn't work.

**Comment by SvenWesterlaken** [comment]
How do you update your pagination in the query parameters? It seems to me the problem resides there.

**Comment by modbender** [comment]
> How do you update your pagination in the query parameters? It seems to me the problem resides there.

@SvenWesterlaken 

Actually it started working after some changes later on, this was a very weird situation

My code was 
```js
const currentPage = computed(() => route.query?.page || 1);

const { data } = await useAsyncData('posts', () => find('posts', {
  pagination: {
    page: unref(currentPage),
    pageSize: 12
  },
  populate: ['featuredImage', 'tags'],
  sort: ['createdAt:desc']
}), {
  watch: [currentPage]
})

const { data: postList, meta} = unref(data);
```

It seems using destructuring assignment was causing the rendered elements to not update.

After removing
```js
const { data: postList, meta} = unref(data);
```

and using `data` directly it started working.

**Comment by SvenWesterlaken** [comment]
@modbender that makes sense as `data` is a ref and unreffing it removes the reactivity for the rest of the code/template. 

Quick tip: If you want a to transform the returned data you could use the transform option in the useAsyncData function. Should be in the same option object as the `watch` property. Or even the `pick` option could be useful if you don't want to expose all then properties returned by the http response. Lastly, using a computed property would also work.
