### ISSUE TITLE
Include a default (or optional) markdown parser for rich text fields

### ISSUE THREAD

**Issue by cantkillemall** [nuxt-modules/strapi#362]
### Is your feature request related to a problem? Please describe.

Strapi is offering rich text fields, that are sent as Markdown within the json objects.
We all have to implement a complete handling of the markdown to turn it to HTML

### Describe the solution you'd like

nuxt/content has already a performant and elegant way of parsing markdown and turn it into HTML, but document based.
Let's imagine a `useStrapiMarkdown` or `useStrapiMarkdownInline` composable, parsing the markdown (inline or not) of a field based on the nuxt/content parser.

Example:

```
interface Restaurant {
  id: number;
  attributes: {
    name: string;
    address: string;
    specialties: string[];
    seats: number;
    openingHours: string;
    menu: string; // rich text field in Markdown
  }
}

const response = await find<Restaurant>('restaurants', { parseMarkdown: attributes.menu})
```
We could then use a `v-html` directive to display the parsed MD.

### Describe alternatives you've considered

nuxt/content, but document-based which is not the case

**Comment by benjamincanac** [comment]
`@nuxt/content` markdown parser has been moved into this module: https://github.com/nuxt-modules/mdc, you can use it to parse markdown from where you want.
