### ISSUE TITLE
Error in Nuxt 3 last release

### ISSUE THREAD

**Issue by pezexd** [nuxt-modules/strapi#366]
### Version
@nuxtjs/strapi: v1.9.3

### Error
nuxt: v3.0.8[nitro] [unhandledRejection] {
  error: {
    status: 500,
    name: 'UnknownError',
    message: '[GET] "url": <no response> fetch failed',
    details: FetchError: [GET] "url": <no response> fetch failed
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async $fetch2 (file:///C:/Users/User/Documents/project/node_modules/.pnpm/ofetch@1.3.3/node_modules/ofetch/dist/shared/ofetch.00501375.mjs:261:15)
        at async C:\Users\User\Documents\project\node_modules\.pnpm\@nuxtjs+strapi@1.9.3\node_modules\@nuxtjs\strapi\dist\runtime\composables\useStrapiClient.mjs:44:14 {
      [cause]: [TypeError]
    }
  }
}

**Comment by angh0r** [comment]
Same here. Clean install. Any Strapi call cause error 500.

**Comment by hangxingfu** [comment]
I also encountered similar errors, but I just changed nuxt.config.ts
```
strapi:{
    url: process.env.STRAPI_URL || "http://127.0.0.1:1337",
    prefix: "/api",
  },
```

url not "localhost"
