### ISSUE TITLE
Where is the 'admin' module option?

### ISSUE THREAD

**Issue by lessainspasorchies** [nuxt-modules/strapi#383]
We used to have the 'admin' option to indicate the path the the Admin Console of Strapi.
I now have an error that this option is unknown:
<img width="1128" alt="Capture d’écran 2024-01-06 à 21 40 58" src="https://github.com/nuxt-modules/strapi/assets/120784744/1b2fd3b7-7151-46fa-ab5a-184ed7dc483a">
The docs aren't mentioning this attribute as well.

**Comment by benjamincanac** [comment]
It just has been released in https://github.com/nuxt-modules/strapi/releases/tag/v1.11.0.
