### ISSUE TITLE
Export types

### ISSUE THREAD

**Issue by MarijnFK** [nuxt-modules/strapi#390]
The types from /dist/runtime/types/ cannot be imported from the package.
Can you include them in the types.d.ts?

**Comment by benjamincanac** [comment]
Have you tried importing from `#ui/types`? https://ui.nuxt.com/getting-started/installation#typescript

**Comment by luke-z** [comment]
Just encountered the same problem :)

**Comment by marius-mcfly** [comment]
Same here 👀

**Comment by mrc-bsllt** [comment]
I think the problem comes from the latest version of Nuxt (3.10.1), because I also have the same problem with i18n types.

**Comment by mrc-bsllt** [comment]
For the time being, the problem is solved by setting this new parameter to false.
https://nuxt.com/blog/v3-10#bundler-module-resolution

**Comment by BayBreezy** [comment]
Thanks for the temp fix. Hopefully it gets resolved soon

**Comment by benjamincanac** [comment]
Are you importing the types from `#ui/types`? https://ui.nuxt.com/getting-started/installation#typescript

**Comment by BayBreezy** [comment]
@benjamincanac , I think you have the repos mixed up?

This is the strapi repo

**Comment by BayBreezy** [comment]
Thank you ❤️

**Comment by benjamincanac** [comment]
@BayBreezy It's been released! Let me know if the problem persists 😊
