### ISSUE TITLE
Strapi v5 Beta

### ISSUE THREAD

**Issue by MarijnFK** [nuxt-modules/strapi#402]
Strapi v5 Beta is out, would be nice to have support for it.
More info here: https://strapi.io/five

**Comment by reslear** [comment]
stapi already been RC

**Comment by tiYusupov** [comment]
any updates?

**Comment by XanderD99** [comment]
FYI: https://github.com/nuxt-modules/strapi/pull/424

**Comment by MarijnFK** [comment]
@XanderD99  awesome, closing this
