### ISSUE TITLE
Strapi impersonation

### ISSUE THREAD

**Issue by IvanWala** [nuxt-modules/strapi#412]
Hello. Is possible to use this module with [strapi impersonation](https://github.com/Fekide/strapi-plugin-impersonation)?

**Comment by benjamincanac** [comment]
I haven't tried but you should be able to use the `setToken` method from the `useStrapiAuth` composable.

**Comment by IvanWala** [comment]
Thank I'm going to try this.

**Comment by benjamincanac** [comment]
Feel free to reopen if you encounter any issue 😊
