### ISSUE TITLE
Dokumentation is broken

### ISSUE THREAD

**Issue by SaschaEdelmann** [nuxt-modules/strapi#420]
The Website with the Dokumentation is not working at the moment. 
It just shows the Navigation and Background. Content is missing:

Issues in Console:
![Bildschirmfoto 2024-06-17 um 15 33 33](https://github.com/nuxt-modules/strapi/assets/169985893/9a649a8a-297d-47a0-9bbd-7ba3686609ba)

**Comment by benjamincanac** [comment]
Sorry about that, this should now be fixed!
