### ISSUE TITLE
QUESTION: find() and filtering by relation 

### ISSUE THREAD

**Issue by MathiasOdlund** [nuxt-modules/strapi#421]
Hey,
I tried to ask my question over at the Nuxt Discord server without much luck.

I have two collection types that has relations with eachother:
- Products
    - Name
    - slug
- Subitems
    - name
    - description
Each Product can have any number of SubItems. Just like SubItems can belong to any number of Products.
While querying for SubItems, I was wondering how I could search for SubItems that belongs to a certain product using the product slug to identify the product.

`
const product = await findOne("products", route.params.id);
`
`
const subItems = await find("subItems", {
filter: someCodeThatTellsMeHowToFindSubItemsUsingTheProductSlug.
});
`

**Comment by BayBreezy** [comment]
@MathiasOdlund Hello,
Sorry that you had to wait this long for a response, did you get an answer?
It is hard to assist since I don't know what the collection relationship look like but I am assuming that there is a many-to-many relationship between product & subitem?

**Comment by MathiasOdlund** [comment]
Hey,
yes, I figured it out 😄
