### ISSUE TITLE
Plans for Strapi 5 Support?

### ISSUE THREAD

**Issue by ram-you** [nuxt-modules/strapi#430]
@atinux @pi0 
@lauriejim @alexandrebodin

Are there any plans to update or port @nuxtjs/strapi to support Strapi 5, now that it is generally available and production-ready?
If so, is there an estimated timeline?

Thanks!

**Comment by benjamincanac** [comment]
It has been implemented already: https://github.com/nuxt-modules/strapi/pull/424.

You can try it out using the [Edge](https://strapi.nuxtjs.org/setup#edge) package.
