### ISSUE TITLE
Unsupported version from install example

### ISSUE THREAD

**Issue by xZyph** [nuxt-modules/strapi#440]
### Version
@nuxtjs/strapi: 1.12.0
nuxt: 3.13.0

### Reproduction Link

https://codesandbox.io/p/devbox/rxycqg

### Steps to reproduce

> npx nuxi@latest init versionIssue && cd versionIssue
_(npm, No)_
> npx nuxi@latest module add strapi

Add to `nuxt.config.ts`:
```
  strapi: {
    url: 'some-strapi-url',
    version: 'v5'
  },
```

Observe issue with 'v5' as value in VS Code.

### What is Expected?

Since the [documentation](https://strapi.nuxtjs.org/setup) example explicitly use `v5` as an example, I would imagine it is expected for this to work without any issues.

### What is actually happening?

I am getting the error:
```
Type '"v5"' is not assignable to type '"v4" | "v3" | undefined'.ts(2322)
(property) version: "v5"
```

**Comment by benjamincanac** [comment]
This hasn't been released yet, you can use the `Edge` package in the meantime: https://strapi.nuxtjs.org/setup#edge

**Comment by benjamincanac** [comment]
You can now use https://github.com/nuxt-modules/strapi/releases/tag/v2.0.0.
