### ISSUE TITLE
Pagination type

### ISSUE THREAD

**Issue by mickaelchanrion** [nuxt-modules/strapi#447]
Hi!
I noticed that the type of [PaginationByPage](https://github.com/nuxt-modules/strapi/blob/6a45a446971585c18a364fd89edd4b91997f1781/src/runtime/types/v4.ts#L12) is incorrect. I think it should be something like: 
```ts
export interface PaginationByPage {
  page: number
  pageSize: number
  pageCount: number
  total: number
}
```

At least, this is the response I get from a strapi 4 instance

### Version
@nuxtjs/strapi: v1.12.0 and v2
nuxt: any

**Comment by olrtg** [comment]
Did you check #398?

**Comment by mickaelchanrion** [comment]
My bad, I didn't scroll enough in the type def file.
I was looking for the type of the pagination object in the response which is `MetaResponsePaginationByPage`, not `PaginationByPage`.
I'm closing now as this is not relevant.
